services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    # No host port mapping needed; API uses internal network
    expose:
      - "11434"
    gpus: all
    volumes:
      - C:\Users\jadec\.ollama:/root/.ollama
    restart: unless-stopped

  api:
    build: .
    container_name: oss20b-api
    environment:
      - APP_API_KEY=${APP_API_KEY}
      - API_KEY_HEADER_NAME=${API_KEY_HEADER_NAME:-x-api-key}
      - OLLAMA_BASE_URL=http://ollama:11434/v1
      - OLLAMA_API_KEY=${OLLAMA_API_KEY:-ollama}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gpt-oss:20b}
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    restart: unless-stopped


